### ISSUE TITLE
File missing in repo

### ISSUE THREAD

**Issue by UffeJakobsen** [mveinot/QtCBM#1]
QtCBM.pro:
include(../qt-solutions/qtsingleapplication/src/qtsingleapplication.pri)

The above file is not present in the repo

**Comment by mveinot** [comment]
QtCBM relies on qt-solutions which provides this and the associated classes. It is available at:
https://git.gitorious.org/qt-solutions/qt-solutions.git

**Comment by UffeJakobsen** [comment]
Thanks

The following is needed for my build to work - I guess that you have diskimage.h and the library installed under /usr/local or something like that.

This diff will make the repo extract and build more self-contained

```
diff --git a/QtCBM.pro b/QtCBM.pro
index d82b449..8d9c006 100644
--- a/QtCBM.pro
+++ b/QtCBM.pro
@@ -41,7 +41,9 @@ win32 {

 !win32 {
         LIBS += -L/usr/local/lib
+        LIBS += -Ldiskimage
         INCLUDEPATH += /usr/local/include
+        INCLUDEPATH += diskimage
 }

 LIBS += -ldiskimage
```

**Comment by UffeJakobsen** [comment]
This issue is closed - thx
