### ISSUE TITLE
Feature request: remember window state

### ISSUE THREAD

**Issue by UffeJakobsen** [mveinot/QtCBM#3]
Feature request: remember window state

It would be nice if QtCBM could remember its window state (geometry, maximized etc) between runs.

**Comment by mveinot** [comment]
Should be an easy add. I'll push this in later today, probably.

**Comment by mveinot** [comment]
I've committed code for this to HEAD. Feel free to merge it with stable if you wish, as it is a very minimal change set. Marking this closed.
