### ISSUE TITLE
FYI: QtCBM packages are now available for Archlinux

### ISSUE THREAD

**Issue by UffeJakobsen** [mveinot/QtCBM#4]
FYI: QtCBM packages are now available for Archlinux

QtCBM is now available in two versions for Archlinux:

1) a stable release based on latest github release
https://aur.archlinux.org/packages/qtcbm/

2) a bleeding edge release based on github HEAD
https://aur.archlinux.org/packages/qtcbm-git/

You might want to update your homepage with this information

/Uffe

**Comment by mveinot** [comment]
That's excellent. I will add this information to the site when a get a moment later today. Thanks!

**Comment by mveinot** [comment]
I've added this information to the downloads page. Cheers! http://c64.mvgrafx.net/?page_id=2
